# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/resume_builder_ai_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&protos/resume_builder_ai_service.proto\x12\rresume.parser\"_\n\x12ParseResumeRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66iletype\x18\x02 \x01(\t\x12\x11\n\tparsetype\x18\x03 \x01(\t\x12\x12\n\nbase64data\x18\x04 \x01(\t\"%\n\x13ParseResumeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\")\n\x18SuggestionSummaryRequest\x12\r\n\x05input\x18\x01 \x01(\t\"+\n\x19SuggestionSummaryResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2\xd3\x01\n\x0fResumeAIService\x12V\n\x0bParseResume\x12!.resume.parser.ParseResumeRequest\x1a\".resume.parser.ParseResumeResponse\"\x00\x12h\n\x11SuggestionSummary\x12\'.resume.parser.SuggestionSummaryRequest\x1a(.resume.parser.SuggestionSummaryResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.resume_builder_ai_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARSERESUMEREQUEST._serialized_start=57
  _PARSERESUMEREQUEST._serialized_end=152
  _PARSERESUMERESPONSE._serialized_start=154
  _PARSERESUMERESPONSE._serialized_end=191
  _SUGGESTIONSUMMARYREQUEST._serialized_start=193
  _SUGGESTIONSUMMARYREQUEST._serialized_end=234
  _SUGGESTIONSUMMARYRESPONSE._serialized_start=236
  _SUGGESTIONSUMMARYRESPONSE._serialized_end=279
  _RESUMEAISERVICE._serialized_start=282
  _RESUMEAISERVICE._serialized_end=493
# @@protoc_insertion_point(module_scope)
